# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(name: 'qq', email: 'qq@gmail.com', password: 'qqdayo', admin: false )
User.create(name: 'aa', email: 'aa@gmail.com', password: 'aadayo', admin: true )
User.create(name: 'ee', email: 'ee@gmail.com', password: 'eedayo', admin: false )
User.create(name: 'rr', email: 'rr@gmail.com', password: 'rrdayo', admin: false )
User.create(name: 'tt', email: 'tt@gmail.com', password: 'ttdayo', admin: false )
User.create(name: 'yy', email: 'yy@gmail.com', password: 'yydayo', admin: false )
User.create(name: 'uu', email: 'uu@gmail.com', password: 'uudayo', admin: false )
User.create(name: 'ii', email: 'ii@gmail.com', password: 'iidayo', admin: false )
User.create(name: 'oo', email: 'oo@gmail.com', password: 'oodayo', admin: false )
User.create(name: 'pp', email: 'pp@gmail.com', password: 'ppdayo', admin: false )
Label.create(name: 'テスト1')
Label.create(name: 'テスト2')
Label.create(name: 'テスト3')
Label.create(name: 'テスト4')
Label.create(name: 'テスト5')
Label.create(name: 'テスト6')
Label.create(name: 'テスト7')
Label.create(name: 'テスト8')
Label.create(name: 'テスト9')
Label.create(name: 'テスト10')
Task.create(title: 'test_title1', status: '完了', user_id: '1', content: 'test_content1', deadline: '002022-07-13-00-00', priority: '低')
Task.create(title: 'test_title2', status: '未着手', user_id: '2', content: 'test_content2', deadline: '002022-07-12-00-00', priority: '中')
Task.create(title: 'test_title3', status: '着手中', user_id: '3', content: 'test_content3', deadline: '002022-07-11-00-00', priority: '高')
Task.create(title: 'test_title4', status: '完了', user_id: '4', content: 'test_content4', deadline: '002022-07-10-00-00', priority: '低')
Task.create(title: 'test_title5', status: '未着手', user_id: '5', content: 'test_content5', deadline: '002022-07-09-00-00', priority: '中')
Task.create(title: 'test_title6', status: '完了', user_id: '6', content: 'test_content6', deadline: '002022-07-08-00-00', priority: '高')
Task.create(title: 'test_title7', status: '着手中', user_id: '7', content: 'test_content7', deadline: '002022-07-07-00-00', priority: '低')
Task.create(title: 'test_title8', status: '未着手', user_id: '8', content: 'test_content8', deadline: '002022-07-06-00-00', priority: '中')
Task.create(title: 'test_title9', status: '完了', user_id: '9', content: 'test_content9', deadline: '002022-07-05-00-00', priority: '高')
Task.create(title: 'test_title10', status: '着手中', user_id: '10', content: 'test_content10', deadline: '002022-07-04-00-00', priority: '低')
